# Generated by Django 3.2.6 on 2022-01-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название пиццы')),
                ('text', models.CharField(max_length=100, verbose_name='Описание пиццы')),
                ('full_tex', models.TextField(verbose_name='Полное описание')),
                ('img', models.ImageField(upload_to='img/', verbose_name='Картинка')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
