# Generated by Django 3.2.6 on 2022-01-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagemenu',
            name='full_tex',
            field=models.TextField(verbose_name='состав'),
        ),
    ]
