# Generated by Django 3.2.6 on 2022-02-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Коментраии', 'verbose_name_plural': 'Коментраии'},
        ),
        migrations.AddField(
            model_name='comments',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mainpagemenu'),
        ),
    ]
